[PRIVILEGES] :sparkles: Add user Privileges
openemp/openemp-api-user pull request #11
Opened 2020-06-04 13:47 UTC by DjihadBengati

2020-06-04 16:11 UTC, chinzou requested changes

2020-06-04 16:11 UTC, chinzou commented on src/main/java/org/openemp/api/user/model/Role.java
> +import javax.persistence.*;
@DjihadBengati, Can you please avoid using wild cards ("*") in imports, for readability reasons.

2020-06-04 16:11 UTC, chinzou commented on src/main/java/org/openemp/api/user/model/Role.java
> -    @OneToMany(cascade = CascadeType.ALL,
Is there a reason why this is not aligned?

2020-06-04 16:11 UTC, chinzou commented on src/test/java/org/openemp/api/user/OpenempUserApiApplicationTests.java
> +	public void testAuthorize() throws Exception {
Can we have these tests in a separate file, something like **OpenEMPSecurityTests.java**

2020-06-04 19:44 UTC, DjihadBengati commented on src/main/java/org/openemp/api/user/model/Role.java
> -    @OneToMany(cascade = CascadeType.ALL,
What do you mean by aligned ?

2020-06-04 19:46 UTC, DjihadBengati commented on src/test/java/org/openemp/api/user/OpenempUserApiApplicationTests.java
> +	public void testAuthorize() throws Exception {
The testAutorize in the OpenEMPSecurityTests.java ?

2020-06-04 22:28 UTC, chinzou commented on src/test/java/org/openemp/api/user/OpenempUserApiApplicationTests.java
> +	public void testAuthorize() throws Exception {
yes, it make sense. isn't?

2020-06-04 22:30 UTC, chinzou commented on src/main/java/org/openemp/api/user/model/Role.java
> -    @OneToMany(cascade = CascadeType.ALL,
I mean, they just look like not at the same level lol, something like this
```           
         private .......
       @OneTo...
```

2020-06-05 07:16 UTC, DjihadBengati commented on src/test/java/org/openemp/api/user/OpenempUserApiApplicationTests.java
> +	public void testAuthorize() throws Exception {
Yes why not ! I will send a commit doing that :)

2020-06-05 08:58 UTC, chinzou approved these changes

2020-06-05 09:00 UTC, merged

2020-06-05 09:02 UTC, chinzou commented
Thanks @DjihadBengati